export type SourceKind =
  | "official_rss"
  | "official_html"
  | "docs_changelog"
  | "status_feed"
  | "github_api"
  | "community_api"
  | "person_feed"
  | "social_gated";

export type SourceReadiness =
  | "ready"
  | "scrape_required"
  | "needs_credentials"
  | "planned"
  | "blocked";

export type MonitoredSource = {
  id: string;
  name: string;
  kind: SourceKind;
  url: string;
  readiness: SourceReadiness;
  cadence: "15m" | "hourly" | "2h" | "daily" | "manual";
  authority: 1 | 2 | 3 | 4 | 5;
  authorityScore: number;
  notes: string;
};

export type MonitoredSubject = {
  id: string;
  name: string;
  type: "lab" | "person" | "community" | "project";
  priority: "P0" | "P1" | "P2";
  importanceScore: 1 | 0.8 | 0.5 | 0.3;
  trustLevel: "official_first" | "mixed" | "alternative_first" | "social_gated";
  freshnessCadence: MonitoredSource["cadence"];
  sourceIds: string[];
  repoSlugs: string[];
  watchTags: string[];
  rationale: string;
};

export type MonitoredRepo = {
  slug: string;
  priority: "P0" | "P1" | "P2";
  category: "official_sdk" | "cookbook" | "agent" | "inference" | "model_hub" | "framework";
  ownerSubjectId?: string;
  rationale: string;
};

export type ScoringSignal = {
  id: string;
  label: string;
  weight: number;
  notes: string;
};

export const sourceRegistryCheckedAt = "2026-05-31";

export const monitoredSources = [
  {
    id: "openai-news",
    name: "OpenAI news RSS",
    kind: "official_rss",
    url: "https://openai.com/news/rss.xml",
    readiness: "ready",
    cadence: "hourly",
    authority: 5,
    authorityScore: 1,
    notes: "Verified RSS endpoint for company, product, research, and safety posts.",
  },
  {
    id: "openai-changelog",
    name: "OpenAI API changelog",
    kind: "docs_changelog",
    url: "https://platform.openai.com/docs/changelog",
    readiness: "ready",
    cadence: "hourly",
    authority: 5,
    authorityScore: 1,
    notes: "HTML docs page; poll by page hash and dated entries.",
  },
  {
    id: "openai-status",
    name: "OpenAI status history",
    kind: "status_feed",
    url: "https://status.openai.com/history.rss",
    readiness: "ready",
    cadence: "15m",
    authority: 4,
    authorityScore: 0.9,
    notes: "Operational incidents can explain downstream API chatter.",
  },
  {
    id: "openai-github-org",
    name: "OpenAI GitHub organization",
    kind: "github_api",
    url: "https://api.github.com/orgs/openai/repos?sort=pushed&per_page=50",
    readiness: "ready",
    cadence: "hourly",
    authority: 4,
    authorityScore: 0.9,
    notes: "Official org repo inventory; use with explicit repo watchlist.",
  },
  {
    id: "openai-x-twitter",
    name: "OpenAI X/Twitter",
    kind: "social_gated",
    url: "https://x.com/OpenAI",
    readiness: "needs_credentials",
    cadence: "manual",
    authority: 3,
    authorityScore: 0.2,
    notes: "User-requested P0 social source; gated until X API access is approved.",
  },
  {
    id: "anthropic-news",
    name: "Anthropic news",
    kind: "official_html",
    url: "https://www.anthropic.com/news",
    readiness: "scrape_required",
    cadence: "hourly",
    authority: 5,
    authorityScore: 1,
    notes: "No RSS link found during endpoint check; scrape cards and canonical URLs.",
  },
  {
    id: "anthropic-changelog",
    name: "Anthropic release notes",
    kind: "docs_changelog",
    url: "https://docs.anthropic.com/en/release-notes/overview",
    readiness: "ready",
    cadence: "hourly",
    authority: 5,
    authorityScore: 1,
    notes: "Claude API release notes; poll for model/API/tooling changes.",
  },
  {
    id: "anthropic-status",
    name: "Anthropic status history",
    kind: "status_feed",
    url: "https://status.anthropic.com/history.rss",
    readiness: "ready",
    cadence: "15m",
    authority: 4,
    authorityScore: 0.9,
    notes: "Official status RSS for Claude platform incidents.",
  },
  {
    id: "anthropic-github-org",
    name: "Anthropic GitHub organization",
    kind: "github_api",
    url: "https://api.github.com/orgs/anthropics/repos?sort=pushed&per_page=50",
    readiness: "ready",
    cadence: "hourly",
    authority: 4,
    authorityScore: 0.9,
    notes: "Official org repo inventory; prioritize cookbook and SDK repos.",
  },
  {
    id: "anthropic-x-twitter",
    name: "Anthropic X/Twitter",
    kind: "social_gated",
    url: "https://x.com/AnthropicAI",
    readiness: "needs_credentials",
    cadence: "manual",
    authority: 3,
    authorityScore: 0.2,
    notes: "User-requested P0 social source; gated until X API access is approved.",
  },
  {
    id: "deepseek-site",
    name: "DeepSeek official site",
    kind: "official_html",
    url: "https://www.deepseek.com/",
    readiness: "scrape_required",
    cadence: "hourly",
    authority: 5,
    authorityScore: 1,
    notes: "Official site fetch succeeds; no RSS/Atom alternate found in local check.",
  },
  {
    id: "deepseek-api-docs",
    name: "DeepSeek API docs",
    kind: "docs_changelog",
    url: "https://api-docs.deepseek.com/",
    readiness: "ready",
    cadence: "hourly",
    authority: 5,
    authorityScore: 1,
    notes: "Official docs fetch succeeds; poll docs sitemap/page hashes for API changes.",
  },
  {
    id: "deepseek-github-org",
    name: "DeepSeek GitHub organization",
    kind: "github_api",
    url: "https://api.github.com/orgs/deepseek-ai/repos?sort=pushed&per_page=50",
    readiness: "ready",
    cadence: "hourly",
    authority: 4,
    authorityScore: 0.9,
    notes: "Official org repo inventory for DeepSeek model and kernel releases.",
  },
  {
    id: "deepseek-x-twitter",
    name: "DeepSeek X/Twitter",
    kind: "social_gated",
    url: "https://x.com/deepseek_ai",
    readiness: "needs_credentials",
    cadence: "manual",
    authority: 3,
    authorityScore: 0.2,
    notes: "User-requested P0 social source; gated until X API access is approved.",
  },
  {
    id: "deepmind-blog",
    name: "Google DeepMind blog",
    kind: "official_html",
    url: "https://deepmind.google/discover/blog/",
    readiness: "scrape_required",
    cadence: "hourly",
    authority: 5,
    authorityScore: 1,
    notes: "RSS candidate returned 404; scrape official blog index.",
  },
  {
    id: "google-ai-changelog",
    name: "Gemini API release notes",
    kind: "docs_changelog",
    url: "https://ai.google.dev/gemini-api/docs/changelog",
    readiness: "ready",
    cadence: "hourly",
    authority: 5,
    authorityScore: 1,
    notes: "Official Gemini API release notes for model and platform changes.",
  },
  {
    id: "meta-ai-blog",
    name: "AI at Meta blog",
    kind: "official_html",
    url: "https://ai.meta.com/blog",
    readiness: "scrape_required",
    cadence: "hourly",
    authority: 5,
    authorityScore: 1,
    notes: "No RSS alternate found; scrape latest blog cards and canonical links.",
  },
  {
    id: "mistral-news",
    name: "Mistral AI news",
    kind: "official_html",
    url: "https://mistral.ai/news/",
    readiness: "scrape_required",
    cadence: "hourly",
    authority: 5,
    authorityScore: 1,
    notes: "News pages are structured HTML; RSS candidate returned 404.",
  },
  {
    id: "mistral-docs",
    name: "Mistral docs",
    kind: "docs_changelog",
    url: "https://docs.mistral.ai/",
    readiness: "planned",
    cadence: "daily",
    authority: 4,
    authorityScore: 0.9,
    notes: "Track docs once a stable changelog path or sitemap contract is selected.",
  },
  {
    id: "xai-news",
    name: "xAI news",
    kind: "official_html",
    url: "https://x.ai/news",
    readiness: "blocked",
    cadence: "manual",
    authority: 5,
    authorityScore: 1,
    notes: "Cloudflare blocked direct fetch from local agent; needs browser/API fallback.",
  },
  {
    id: "xai-docs",
    name: "xAI docs",
    kind: "docs_changelog",
    url: "https://docs.x.ai/docs/overview",
    readiness: "ready",
    cadence: "daily",
    authority: 4,
    authorityScore: 0.9,
    notes: "Docs fetch succeeds; use sitemap/page hash until release notes are located.",
  },
  {
    id: "huggingface-blog-rss",
    name: "Hugging Face blog RSS",
    kind: "official_rss",
    url: "https://huggingface.co/blog/feed.xml",
    readiness: "ready",
    cadence: "hourly",
    authority: 5,
    authorityScore: 1,
    notes: "Official blog RSS for ecosystem and product announcements.",
  },
  {
    id: "huggingface-status-rss",
    name: "Hugging Face status feed",
    kind: "status_feed",
    url: "https://status.huggingface.co/feed",
    readiness: "ready",
    cadence: "15m",
    authority: 4,
    authorityScore: 0.9,
    notes: "Status page advertises RSS at /feed.",
  },
  {
    id: "huggingface-models-api",
    name: "Hugging Face models API",
    kind: "community_api",
    url: "https://huggingface.co/api/models?sort=likes&direction=-1&limit=50",
    readiness: "ready",
    cadence: "2h",
    authority: 3,
    authorityScore: 0.75,
    notes: "Use likes/downloads sorting; trending sort is not accepted by the API.",
  },
  {
    id: "github-api",
    name: "GitHub REST API",
    kind: "github_api",
    url: "https://api.github.com",
    readiness: "ready",
    cadence: "hourly",
    authority: 4,
    authorityScore: 0.9,
    notes: "Collect repo metadata, releases, pushed_at, issues, PRs, and star velocity.",
  },
  {
    id: "hn-algolia",
    name: "Hacker News Algolia API",
    kind: "community_api",
    url: "https://hn.algolia.com/api/v1/search_by_date?query=AI&tags=story",
    readiness: "ready",
    cadence: "2h",
    authority: 2,
    authorityScore: 0.6,
    notes: "Good discussion-volume proxy; always dedupe against canonical story URLs.",
  },
  {
    id: "hn-firebase",
    name: "Hacker News Firebase API",
    kind: "community_api",
    url: "https://hacker-news.firebaseio.com/v0/topstories.json",
    readiness: "ready",
    cadence: "2h",
    authority: 2,
    authorityScore: 0.6,
    notes: "Use for top-story ids and item metadata when Algolia freshness lags.",
  },
  {
    id: "arxiv-api",
    name: "arXiv API",
    kind: "community_api",
    url: "https://export.arxiv.org/api/query",
    readiness: "ready",
    cadence: "daily",
    authority: 3,
    authorityScore: 0.75,
    notes: "Start with cs.AI, cs.CL, cs.LG; add author filters after subject registry settles.",
  },
  {
    id: "paperswithcode",
    name: "Papers with Code",
    kind: "community_api",
    url: "https://paperswithcode.com/api/v1/papers/",
    readiness: "planned",
    cadence: "daily",
    authority: 3,
    authorityScore: 0.75,
    notes: "Endpoint returned HTML in local check; verify current API contract before collector work.",
  },
  {
    id: "karpathy-github-user",
    name: "Andrej Karpathy GitHub",
    kind: "person_feed",
    url: "https://api.github.com/users/karpathy/repos?sort=pushed&per_page=25",
    readiness: "ready",
    cadence: "daily",
    authority: 3,
    authorityScore: 0.75,
    notes: "Poll repo pushes and new repos; X/YouTube remain optional gated sources.",
  },
  {
    id: "karpathy-site",
    name: "Andrej Karpathy site",
    kind: "person_feed",
    url: "https://karpathy.ai/",
    readiness: "scrape_required",
    cadence: "daily",
    authority: 3,
    authorityScore: 0.75,
    notes: "Static personal site; poll page hash and outbound project links.",
  },
  {
    id: "karpathy-x-twitter",
    name: "Andrej Karpathy X/Twitter",
    kind: "social_gated",
    url: "https://x.com/karpathy",
    readiness: "needs_credentials",
    cadence: "manual",
    authority: 3,
    authorityScore: 0.2,
    notes: "User-requested P0 person source; use GitHub/site as substitutes without X API.",
  },
  {
    id: "simonw-blog-atom",
    name: "Simon Willison Atom feed",
    kind: "person_feed",
    url: "https://simonwillison.net/atom/everything/",
    readiness: "ready",
    cadence: "hourly",
    authority: 3,
    authorityScore: 0.75,
    notes: "High-signal practitioner feed with stable Atom output.",
  },
  {
    id: "simonw-github",
    name: "Simon Willison GitHub",
    kind: "person_feed",
    url: "https://api.github.com/users/simonw/repos?sort=pushed&per_page=25",
    readiness: "ready",
    cadence: "daily",
    authority: 2,
    authorityScore: 0.6,
    notes: "Useful for sqlite-utils, llm, datasette, and tooling release signals.",
  },
  {
    id: "deeplearning-ai-batch",
    name: "DeepLearning.AI The Batch",
    kind: "person_feed",
    url: "https://www.deeplearning.ai/the-batch/",
    readiness: "scrape_required",
    cadence: "daily",
    authority: 3,
    authorityScore: 0.75,
    notes: "Andrew Ng-associated newsletter; no /feed endpoint found in local check.",
  },
  {
    id: "twitter-x-api",
    name: "X/Twitter API",
    kind: "social_gated",
    url: "https://developer.x.com/en/docs",
    readiness: "needs_credentials",
    cadence: "manual",
    authority: 2,
    authorityScore: 0.2,
    notes: "Keep optional until API credentials, costs, and rate limits are approved.",
  },
] satisfies MonitoredSource[];

export const monitoredSubjects = [
  {
    id: "openai",
    name: "OpenAI",
    type: "lab",
    priority: "P0",
    importanceScore: 1,
    trustLevel: "official_first",
    freshnessCadence: "hourly",
    sourceIds: [
      "openai-news",
      "openai-changelog",
      "openai-status",
      "openai-github-org",
      "openai-x-twitter",
    ],
    repoSlugs: ["openai/openai-cookbook", "openai/openai-python", "openai/openai-node"],
    watchTags: ["models", "api", "agents", "reasoning", "safety", "evals"],
    rationale: "Highest product and ecosystem impact; multiple stable first-party feeds.",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    type: "lab",
    priority: "P0",
    importanceScore: 1,
    trustLevel: "official_first",
    freshnessCadence: "hourly",
    sourceIds: [
      "anthropic-news",
      "anthropic-changelog",
      "anthropic-status",
      "anthropic-github-org",
      "anthropic-x-twitter",
    ],
    repoSlugs: [
      "anthropics/anthropic-cookbook",
      "anthropics/anthropic-sdk-python",
      "anthropics/anthropic-sdk-typescript",
    ],
    watchTags: ["claude", "api", "agents", "safety", "model-context-protocol"],
    rationale: "Model/API releases and MCP work directly affect developer workflows.",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    type: "lab",
    priority: "P0",
    importanceScore: 1,
    trustLevel: "official_first",
    freshnessCadence: "hourly",
    sourceIds: ["deepseek-site", "deepseek-api-docs", "deepseek-github-org", "deepseek-x-twitter"],
    repoSlugs: ["deepseek-ai/DeepSeek-R1", "deepseek-ai/DeepSeek-V3", "deepseek-ai/DeepGEMM"],
    watchTags: ["models", "reasoning", "open-weights", "api", "kernels"],
    rationale: "Human-selected P0 subject; official site/docs and GitHub are pollable, social is gated.",
  },
  {
    id: "google-deepmind",
    name: "Google DeepMind",
    type: "lab",
    priority: "P1",
    importanceScore: 0.8,
    trustLevel: "official_first",
    freshnessCadence: "hourly",
    sourceIds: ["deepmind-blog", "google-ai-changelog", "github-api"],
    repoSlugs: ["google-gemini/cookbook", "google-gemini/gemini-cli"],
    watchTags: ["gemini", "research", "agents", "coding", "multimodal"],
    rationale: "Research announcements and Gemini API changes are high-impact but need HTML scraping.",
  },
  {
    id: "meta-ai",
    name: "Meta AI",
    type: "lab",
    priority: "P1",
    importanceScore: 0.8,
    trustLevel: "official_first",
    freshnessCadence: "hourly",
    sourceIds: ["meta-ai-blog", "github-api"],
    repoSlugs: ["pytorch/pytorch"],
    watchTags: ["llama", "open-source", "research", "infrastructure"],
    rationale: "Open model and infra signals matter; official blog lacks a verified feed.",
  },
  {
    id: "mistral",
    name: "Mistral AI",
    type: "lab",
    priority: "P1",
    importanceScore: 0.8,
    trustLevel: "official_first",
    freshnessCadence: "hourly",
    sourceIds: ["mistral-news", "mistral-docs", "github-api"],
    repoSlugs: [],
    watchTags: ["open-models", "enterprise", "agents", "coding", "retrieval"],
    rationale: "Fast product/research cadence; initial collector should scrape official news.",
  },
  {
    id: "xai",
    name: "xAI",
    type: "lab",
    priority: "P1",
    importanceScore: 0.8,
    trustLevel: "mixed",
    freshnessCadence: "daily",
    sourceIds: ["xai-news", "xai-docs", "twitter-x-api"],
    repoSlugs: [],
    watchTags: ["grok", "api", "models", "real-time"],
    rationale: "High relevance, but official news is blocked from simple fetch and social is gated.",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    type: "lab",
    priority: "P1",
    importanceScore: 0.8,
    trustLevel: "official_first",
    freshnessCadence: "hourly",
    sourceIds: [
      "huggingface-blog-rss",
      "huggingface-status-rss",
      "huggingface-models-api",
      "github-api",
    ],
    repoSlugs: [
      "huggingface/transformers",
      "huggingface/smolagents",
      "huggingface/huggingface_hub",
    ],
    watchTags: ["models", "datasets", "agents", "inference", "open-source"],
    rationale: "Best proxy for open model and tooling movement; strong official/API coverage.",
  },
  {
    id: "karpathy",
    name: "Andrej Karpathy",
    type: "person",
    priority: "P0",
    importanceScore: 1,
    trustLevel: "alternative_first",
    freshnessCadence: "daily",
    sourceIds: ["karpathy-github-user", "karpathy-site", "karpathy-x-twitter"],
    repoSlugs: ["karpathy/nanochat", "karpathy/llm.c"],
    watchTags: ["education", "llm-from-scratch", "agents", "coding"],
    rationale: "High signal for practitioner adoption and education-oriented implementation patterns.",
  },
  {
    id: "simon-willison",
    name: "Simon Willison",
    type: "person",
    priority: "P1",
    importanceScore: 0.8,
    trustLevel: "alternative_first",
    freshnessCadence: "hourly",
    sourceIds: ["simonw-blog-atom", "simonw-github"],
    repoSlugs: ["simonw/llm", "simonw/datasette"],
    watchTags: ["tools", "evals", "security", "prompt-injection", "local-llms"],
    rationale: "Stable public feeds and strong early commentary on practical AI tooling.",
  },
  {
    id: "andrew-ng",
    name: "Andrew Ng",
    type: "person",
    priority: "P2",
    importanceScore: 0.5,
    trustLevel: "alternative_first",
    freshnessCadence: "daily",
    sourceIds: ["deeplearning-ai-batch", "twitter-x-api"],
    repoSlugs: [],
    watchTags: ["education", "applications", "industry", "courses"],
    rationale: "Useful for adoption and education signals; direct pollable sources are weaker.",
  },
  {
    id: "yann-lecun",
    name: "Yann LeCun",
    type: "person",
    priority: "P2",
    importanceScore: 0.5,
    trustLevel: "social_gated",
    freshnessCadence: "daily",
    sourceIds: ["twitter-x-api", "github-api"],
    repoSlugs: ["ylecun/yastro"],
    watchTags: ["research", "open-source", "world-models", "reasoning"],
    rationale: "Influential research voice; mostly social-gated for current commentary.",
  },
] satisfies MonitoredSubject[];

export const monitoredRepos = [
  {
    slug: "deepseek-ai/DeepSeek-R1",
    priority: "P0",
    category: "model_hub",
    ownerSubjectId: "deepseek",
    rationale: "Human-selected P0 subject repo; official reasoning model release signal.",
  },
  {
    slug: "deepseek-ai/DeepSeek-V3",
    priority: "P0",
    category: "model_hub",
    ownerSubjectId: "deepseek",
    rationale: "Official DeepSeek model repo; watch releases, commits, and issues.",
  },
  {
    slug: "deepseek-ai/DeepGEMM",
    priority: "P1",
    category: "inference",
    ownerSubjectId: "deepseek",
    rationale: "Kernel/performance repo for DeepSeek ecosystem movement.",
  },
  {
    slug: "openai/openai-cookbook",
    priority: "P0",
    category: "cookbook",
    ownerSubjectId: "openai",
    rationale: "Often reflects new API patterns before they are widely copied.",
  },
  {
    slug: "openai/openai-python",
    priority: "P0",
    category: "official_sdk",
    ownerSubjectId: "openai",
    rationale: "SDK releases expose API surface changes quickly.",
  },
  {
    slug: "anthropics/anthropic-cookbook",
    priority: "P0",
    category: "cookbook",
    ownerSubjectId: "anthropic",
    rationale: "Recipes signal Claude workflow changes and recommended patterns.",
  },
  {
    slug: "google-gemini/gemini-cli",
    priority: "P0",
    category: "agent",
    ownerSubjectId: "google-deepmind",
    rationale: "Large, fast-moving official coding agent repo.",
  },
  {
    slug: "huggingface/transformers",
    priority: "P0",
    category: "model_hub",
    ownerSubjectId: "huggingface",
    rationale: "Core ecosystem repo; releases track model and inference direction.",
  },
  {
    slug: "huggingface/smolagents",
    priority: "P1",
    category: "agent",
    ownerSubjectId: "huggingface",
    rationale: "Small agent framework with strong alignment to code-agent workflows.",
  },
  {
    slug: "langchain-ai/langgraph",
    priority: "P0",
    category: "agent",
    rationale: "Strong proxy for production agent orchestration adoption.",
  },
  {
    slug: "modelcontextprotocol/specification",
    priority: "P0",
    category: "framework",
    rationale: "Protocol changes can drive tool and agent interoperability news.",
  },
  {
    slug: "modelcontextprotocol/servers",
    priority: "P1",
    category: "framework",
    rationale: "Server ecosystem changes show MCP adoption breadth.",
  },
  {
    slug: "vllm-project/vllm",
    priority: "P0",
    category: "inference",
    rationale: "High-signal inference serving project for deployment trends.",
  },
  {
    slug: "ollama/ollama",
    priority: "P0",
    category: "inference",
    rationale: "Local inference adoption proxy with high release/activity velocity.",
  },
  {
    slug: "ggml-org/llama.cpp",
    priority: "P0",
    category: "inference",
    rationale: "Foundational local inference repo; fast response to new open models.",
  },
  {
    slug: "ml-explore/mlx",
    priority: "P1",
    category: "framework",
    rationale: "Apple silicon model experimentation and local inference signal.",
  },
  {
    slug: "microsoft/autogen",
    priority: "P1",
    category: "agent",
    rationale: "Enterprise agent framework; include despite slower recent push cadence.",
  },
  {
    slug: "pytorch/pytorch",
    priority: "P1",
    category: "framework",
    ownerSubjectId: "meta-ai",
    rationale: "Core ML framework; use only for filtered release and major-change signals.",
  },
] satisfies MonitoredRepo[];

export const scoringRubric = [
  {
    id: "source-authority",
    label: "Source authority",
    weight: 25,
    notes: "Official lab/docs/status > official repo > reputable practitioner > community discussion.",
  },
  {
    id: "recency",
    label: "Recency",
    weight: 20,
    notes: "Boost items inside 24h; decay after 7d unless repo velocity remains high.",
  },
  {
    id: "repo-velocity",
    label: "Repo velocity",
    weight: 20,
    notes: "Stars, pushed_at, releases, issue/PR activity, and maintainer density.",
  },
  {
    id: "cross-source-corroboration",
    label: "Cross-source corroboration",
    weight: 15,
    notes: "Same topic appearing across official, GitHub, HN/arXiv/HF, or person feeds.",
  },
  {
    id: "developer-impact",
    label: "Developer impact",
    weight: 15,
    notes: "API/model/tooling changes that require migration or unlock new workflows.",
  },
  {
    id: "novelty-risk",
    label: "Novelty and risk adjustment",
    weight: 5,
    notes: "Penalize thin duplicates and unverified social-only claims; flag instead of suppressing.",
  },
] satisfies ScoringSignal[];
